### ISSUE TITLE
arm-linux  gpu库编译出错

### ISSUE THREAD

**Issue by leeburt** [zhy520xp/mace-makefile-project#9]
出错的log如下：
g++  -O3 -std=c++11 -fpermissive -DMACE_ENABLE_OPENCL -I.. -I../include/protobuf3.4.0 -I../include -I../include/opencl_clhpp -I../include/opencl20 -I../mace -I../mace/publics     -c -o ../mace/core/runtime/opencl/opencl_runtime.o ../mace/core/runtime/opencl/opencl_runtime.cc
../mace/core/runtime/opencl/opencl_runtime.cc: In constructor ‘mace::OpenCLRuntime::OpenCLRuntime()’:
../mace/core/runtime/opencl/opencl_runtime.cc:383:47: error: call of overloaded ‘Context(<brace-enclosed initializer list>, int*, std::nullptr_t, std::nullptr_t, cl_int*)’ is ambiguous
                         nullptr, nullptr, &err));
                                               ^
../mace/core/runtime/opencl/opencl_runtime.cc:383:47: note: candidates are:
In file included from ../mace/core/runtime/opencl/cl2_header.h:23:0,
                 from ../mace/core/runtime/opencl/opencl_runtime.h:26,
                 from ../mace/core/runtime/opencl/opencl_runtime.cc:15:
../include/opencl_clhpp/include/CL/cl2.hpp:2674:5: note: cl::Context::Context(const cl::Device&, cl_context_properties*, void (*)(const char*, const void*, cl::size_type, void*), void*, cl_int*)
     Context(
     ^
../include/opencl_clhpp/include/CL/cl2.hpp:2643:5: note: cl::Context::Context(cl::vector<cl::Device>&, cl_context_properties*, void (*)(const char*, const void*, cl::size_type, void*), void*, cl_int*)
     Context(
     ^
../mace/core/runtime/opencl/opencl_runtime.cc:393:49: error: call of overloaded ‘Context(<brace-enclosed initializer list>, int*, std::nullptr_t, std::nullptr_t, cl_int*)’ is ambiguous
                           nullptr, nullptr, &err));
                                                 ^
../mace/core/runtime/opencl/opencl_runtime.cc:393:49: note: candidates are:
In file included from ../mace/core/runtime/opencl/cl2_header.h:23:0,
                 from ../mace/core/runtime/opencl/opencl_runtime.h:26,
                 from ../mace/core/runtime/opencl/opencl_runtime.cc:15:
../include/opencl_clhpp/include/CL/cl2.hpp:2674:5: note: cl::Context::Context(const cl::Device&, cl_context_properties*, void (*)(const char*, const void*, cl::size_type, void*), void*, cl_int*)
     Context(
     ^
../include/opencl_clhpp/include/CL/cl2.hpp:2643:5: note: cl::Context::Context(cl::vector<cl::Device>&, cl_context_properties*, void (*)(const char*, const void*, cl::size_type, void*), void*, cl_int*)
     Context(
     ^
../mace/core/runtime/opencl/opencl_runtime.cc:396:70: error: call of overloaded ‘Context(<brace-enclosed initializer list>, std::nullptr_t, std::nullptr_t, std::nullptr_t, cl_int*)’ is ambiguous
           new cl::Context({*device_}, nullptr, nullptr, nullptr, &err));
                                                                      ^
../mace/core/runtime/opencl/opencl_runtime.cc:396:70: note: candidates are:
In file included from ../mace/core/runtime/opencl/cl2_header.h:23:0,
                 from ../mace/core/runtime/opencl/opencl_runtime.h:26,
                 from ../mace/core/runtime/opencl/opencl_runtime.cc:15:
../include/opencl_clhpp/include/CL/cl2.hpp:2674:5: note: cl::Context::Context(const cl::Device&, cl_context_properties*, void (*)(const char*, const void*, cl::size_type, void*), void*, cl_int*)
     Context(
     ^
../include/opencl_clhpp/include/CL/cl2.hpp:2643:5: note: cl::Context::Context(cl::vector<cl::Device>&, cl_context_properties*, void (*)(const char*, const void*, cl::size_type, void*), void*, cl_int*)
     Context(
     ^
make: *** [../mace/core/runtime/opencl/opencl_runtime.o] Error 1

**Comment by zhy520xp** [comment]
你的编译器应该不支持c++11吧

**Comment by leeburt** [comment]
编译器时支持的c++11的。对于编译器还需要什么条件吗？

**Comment by zhy520xp** [comment]
把c++11改成c++14试试。

**Comment by leeburt** [comment]
我的编译器目前只支持c++11，请问有什么其他方法吗？

**Comment by leeburt** [comment]
我已经编过了，将三处new cl::Context({*device_}, (cl_context_properties*)context_properties.data(),
                        nullptr, nullptr, &err)改为new cl::Context(*device_, (cl_context_properties*)context_properties.data(),
                        nullptr, nullptr, &err)即可。
